### PR TITLE
Fully qualify WP_Filesystem

### PR DESCRIPTION
**Pull request by szepeviktor**
small backslash, big 🐛

@Kubitomakita

### CODE REVIEW

**Comment by jakubmikita** [comment]
Hmm on which PHP version is it failing?

I'm going to add the test matrix to check as well

**Comment by szepeviktor** [comment]
On _reading with my eyes_ version :)

The cause is `namespace Micropackage\Filesystem;`

**Comment by szepeviktor** [comment]
You may use @phpstan to detect countless problems in the code.

```php
/**
 * @method bool chown( string $file, string|int $owner, bool $recursive = false )
 */
class Filesystem {
```

Adding magic method signatures helps static analysis.

**Comment by jakubmikita** [comment]
Well, in general, I'd agree, but it's not failing in this case :)

Just pushed new test action and tested from PHP 5.6 up to 7.4: https://github.com/micropackage/filesystem/actions/runs/36284024

I have used this package already in one project and works fine as well.

**Comment by szepeviktor** [comment]
I see!
That is not a class instantiation but a call to a [global function](https://developer.wordpress.org/reference/functions/wp_filesystem/).

The CaSing misled me.

**Pull request closed without merging**
